#pragma once
/*-------------------------------------------
This file is auto generated by gen_emojiSet_to_cpp_Class.py,
DO NOT MODIFY IT MANUALLY.
Generated on 2024-12-06 23:23:06
-------------------------------------------*/
#include <cstdint>
#include <array>

class emoji
{
public:
    uint16_t id;
    std::array<std::array<uint8_t, 8>, 8> content;
};

class emojiSet
{
public:
    static const uint8_t MAX_LEYE_COUNT  = 27;
    static const uint8_t MAX_REYE_COUNT  = 27;
    static const uint8_t MAX_MOUTH_COUNT = 32;
    static const uint8_t MAX_FACE_COUNT  = 5;

    emoji LEye[MAX_LEYE_COUNT + 1];
    emoji REye[MAX_REYE_COUNT + 1];
    emoji Mouth[MAX_MOUTH_COUNT + 1];
    emoji Face[MAX_FACE_COUNT + 1];
    emoji EmptyPart;
    emojiSet();
};
